 default: &default
   dispatchers:
     - polling_interval: 1
       batch_size: 500
   workers:
     - queues: "*"
       threads: 3
       polling_interval: 2
     - queues: [ real_time, background ]
       threads: 5
       processes: 1
       polling_interval: 0.1

 development:
  <<: *default

 test:
  <<: *default

 production:
  <<: *default
